// client/src/search-bar/SearchBar.jsx
import React, { useState } from "react";
import { TextField, IconButton } from '@mui/material';
import SearchIcon from '@mui/icons-material/Search';

import "./SearchBar.css";

/**
 * SearchBar component for performing product searches.
 * Renders an input field and search button. Triggers a search action
 * based on user input, calling the `onSearch` callback provided as a prop.
 * 
 * @param {Object} props - Component properties.
 * @param {Function} props.onSearch - Callback function triggered on search action.
 */
const SearchBar = ({ onSearch }) => {
  const [searchTerm, setSearchTerm] = useState(""); // State to store the search term entered by the user.

  /**
   * Triggers the search action.
   * Calls the `onSearch` function with the current `searchTerm` trimmed and converted to lowercase.
   */
  const handleSearch = () => {
    onSearch(searchTerm.trim().toLowerCase());
  };

  /**
   * Updates the `searchTerm` state as the user types.
   * @param {Object} event - The event object generated by the input field's onChange event.
   */
  const handleChange = (event) => {
    setSearchTerm(event.target.value);
  };

  /**
   * Executes the search action on pressing the Enter key.
   * @param {Object} event - The event object generated by the input field's onKeyPress event.
   */
  const handleKeyPress = (event) => {
    if (event.key === "Enter") {
      handleSearch();
    }
  };

  return (
    <div style={{ display: 'flex', alignItems: 'center' }} className="search-bar-container">
      {/* Text field for entering search term */}
      <TextField
        fullWidth
        variant="outlined"
        placeholder="Search"
        value={searchTerm}
        onChange={handleChange}
        onKeyPress={handleKeyPress}
        InputProps={{
          style: {
            backgroundColor: "#f0f0f0", // Background color
            borderRadius: "10px", // Rounded corners
            paddingLeft: "15px", // Left padding
          },
        }}
      />
      <IconButton onClick={handleSearch} style={{ marginLeft: "-40px" }}>
        <SearchIcon />
      </IconButton>
    </div>
  );
};

export default SearchBar